safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "John Casey"

siteTitle: "Commonjava"
projectTitle: "Weft"
tagline: "CDI-Thread/Executor Provider"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
