safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"

title: "Commonjava :: Weft"
tagline: "CDI-Thread/Executor Provider"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org