safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"

siteTitle: "Commonjava"
projectTitle: " :: Weft"
tagline: "CDI-Thread/Executor Provider"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org