#
# Copyright (C) 2011-2023 Red Hat, Inc. (https://github.com/Commonjava/weft)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: maven push

on: [push]

jobs:
  build:
    name: Maven deploy
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx4096m -Xms2048m -XX:MaxMetaspaceSize=4096m -Xss8m"
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - uses: s4u/maven-settings-action@v2.8.0
      with:
        sonatypeSnapshots: true

    - uses: s4u/maven-settings-action@v2.8.0
      if: ${{ github.event_name == 'push' }}
      with:
        servers: |
          [{
              "id": "central-portal-snapshots",
              "username": "${{ secrets.SONATYPE_BOT_USERNAME }}",
              "password": "${{ secrets.SONATYPE_BOT_TOKEN }}"
          }]

    - name: Deploy the artifact
      if: ${{ github.event_name == 'push' }}
      run: mvn help:effective-settings -B -V clean deploy -e