# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Merge / Push Build

on: [push]

jobs:
  publish-snapshot:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B -e deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Commonjava/weft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
